# Example configuration file for CrimePulse project
# Copy this file to Config.toml and fill in the actual values

# MongoDB Configuration (used by auth and complaint services)
MONGO_URI = "mongodb+srv://username:password@cluster.mongodb.net/?retryWrites=true&w=majority&appName=YourAppName"

# Auth Service Configuration
[auth]
DB_NAME = "Accounts"
COLLECTION_ADMINS = "Admins"
COLLECTION_REGISTEREDUSERS = "RegisteredUsers"
COLLECTION_UNREGISTEREDUSERS = "UnregisteredUsers"
PORT = 8082
SERVER_URL = "http://localhost:8082"
FRONTEND_AUTH_URL = "http://localhost:8080"

# Complaint Service Configuration
[complaint]
DB_NAME = "Complaints"
COLLECTION_ASSAULT = "Assault"
COLLECTION_CYBERCRIME = "CyberCrime"
COLLECTION_MISSINGPERSON = "MissingPerson"
COLLECTION_THEFT = "Theft"
COLLECTION_OTHER = "Other"
PORT = 8081
SERVER_URL = "http://localhost:8081"
FRONTEND_COMPLAINT_URL = "http://localhost:8080"

# Cloudinary Configuration (for complaint service)
CLOUDINARY_CLOUD_NAME = "your_cloud_name"
CLOUDINARY_API_KEY = "your_api_key"
CLOUDINARY_API_SECRET = "your_api_secret"
CLOUDINARY_URL = "cloudinary://your_api_key:your_api_secret@your_cloud_name"

# Newsfeed Service Configuration
[newsfeed]
NEWS_API_KEY = "your_news_api_key_here"